name: Test Version

on:
  workflow_dispatch:
    inputs:

jobs:
  test:

    runs-on: ubuntu-latest

    outputs:
      gameClientVersion: ${{ steps.gameClient.outputs.version }}
      patchVersion: ${{ steps.patch.outputs.version }}
      modVersion: v${{ steps.mod.outputs.version }}
      commitish: ${{ steps.commitish.outputs.sha }}
      releaseVersion: ${{ steps.currentrelease.outputs.name }}


    steps:
      - name: current release
        id: currentrelease
        uses: timcosgrove/fetch-latest-release@bfc69dd9892f644ff740234d8b8945f226f15a47
        with:
          github_token: ${{ github.token }}
      - name: checkout onelife
        uses: actions/checkout@v3
        with:
          repository: jasonrohrer/OneLife
          path: OneLife
      - name: Get Game Client Version
        id: gameClient
        run: echo "version="`grep versionNumber OneLife/gameSource/game.cpp | head -1 | sed -e 's/[^0-9]*//g'` >> "$GITHUB_OUTPUT"
      - name: checkout patches
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: fetch tags
        run: git fetch origin "+refs/tags/*:refs/tags/*"
      - name: get patch version number
        id: patch
        run: echo "version="`git for-each-ref --sort=-authordate --sort=-creatordate --format '%(refname:short)' --count=1 refs/tags/v* | sed -e 's/v//'` >> "$GITHUB_OUTPUT" >> "$GITHUB_OUTPUT"
      - name: Compose version
        id: mod
        run: echo "version=${{ steps.gameClient.outputs.version}}.${{ steps.patch.outputs.version }}" >> "$GITHUB_OUTPUT"
      - name: Target Commit
        id: commitish
        run: echo "sha="`git log -1 --pretty=format:%H v${{ steps.patch.outputs.version }}` >> "$GITHUB_OUTPUT"
      - name: report
        run: echo "${{ steps.mod.outputs.version }} ${{ steps.commitish.outputs.name }}"
      - name: Windows filename
        id: windows
        run: echo "filename=WonLife-test-${{ steps.mod.outputs.version}}.zip" >> "$GITHUB_OUTPUT"
      - name: MacOSX filename
        id: macosx
        run: echo "filename=WonLifeMacOSX-test-${{ steps.mod.outputs.version}}.zip" >> "$GITHUB_OUTPUT"

  release:
    needs: test
    if: needs.test.outputs.modVersion != needs.test.outputs.releaseVersion

    runs-on: ubuntu-latest

    steps:
      - name: report
        run: echo "${{ needs.test.outputs.modVersion }} ${{ needs.test.outputs.releaseVersion }}"
